# Inspected SpeechBrain v1.0.3 speechbrain/lobes/models/ECAPA_TDNN.py.
from collections.abc import Mapping
from typing import Self
from torch import Tensor
class ECAPA_TDNN:
    def __init__(self,*,input_size:int,channels:list[int],kernel_sizes:list[int],dilations:list[int],attention_channels:int,lin_neurons:int)->None: ...
    def __call__(self,features:Tensor,lengths:Tensor)->Tensor: ...
    def load_state_dict(self,state_dict:Mapping[str,Tensor],*,strict:bool)->object: ...
    def eval(self)->Self: ...
    def cpu(self)->Self: ...
