import { apiFetch } from './http'
import { parseCloudSpeechQuote, parseCloudSpeechTrialsResponse, parseCreateCloudSpeechVoiceProfileRequest, parseSpeechVoiceProfile, parseSpeechCloneTrialRequest, parseCreateAudiobookRequest, parseCreateAudiobookAuditionRequest, parseAudiobookAuditionOptions, parseCreateAudiobookRepairRequest, parseAudiobookCloudControlRequest } from './contracts'
import type { CloudSpeechQuote, CloudSpeechTrial, CreateCloudSpeechVoiceProfileRequest, SpeechVoiceProfile, SpeechCloneTrialRequest, CreateAudiobookRequest, CreateAudiobookAuditionRequest, AudiobookAuditionOptions, CreateAudiobookRepairRequest, AudiobookCloudControlRequest } from './contracts'
function json(body:unknown,signal?:AbortSignal):RequestInit{return{method:'POST',signal,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}}
function id(value:string){if(!/^[0-9a-f]{32}$/.test(value))throw new TypeError('Invalid speech workflow identifier');return value}
function index(value:number){if(!Number.isInteger(value)||value<0||value>99)throw new TypeError('Invalid chapter index');return value}
export function createCloudSpeechProfile(body:CreateCloudSpeechVoiceProfileRequest,signal?:AbortSignal):Promise<SpeechVoiceProfile>{return apiFetch('/api/voice-profiles/cloud',json(parseCreateCloudSpeechVoiceProfileRequest(body),signal),parseSpeechVoiceProfile)}
export async function listCloudTrials(profileId:string,signal?:AbortSignal):Promise<CloudSpeechTrial[]>{const response=await apiFetch(`/api/speech-clone/profiles/${id(profileId)}/trials`,{signal},parseCloudSpeechTrialsResponse);return response.trials??[]}
export function quoteTrial(body:SpeechCloneTrialRequest,signal?:AbortSignal):Promise<CloudSpeechQuote>{return apiFetch('/api/speech-clone/quote',json(parseSpeechCloneTrialRequest(body),signal),parseCloudSpeechQuote)}
export function quoteBook(body:CreateAudiobookRequest,signal?:AbortSignal):Promise<CloudSpeechQuote>{return apiFetch('/api/audiobooks/quote',json(parseCreateAudiobookRequest(body),signal),parseCloudSpeechQuote)}
export function quoteAudition(body:CreateAudiobookAuditionRequest,signal?:AbortSignal):Promise<CloudSpeechQuote>{return apiFetch('/api/audiobooks/auditions/quote',json(parseCreateAudiobookAuditionRequest(body),signal),parseCloudSpeechQuote)}
export function quoteSavedAudition(bookId:string,body:AudiobookAuditionOptions,signal?:AbortSignal):Promise<CloudSpeechQuote>{return apiFetch(`/api/audiobooks/${id(bookId)}/auditions/quote`,json(parseAudiobookAuditionOptions(body),signal),parseCloudSpeechQuote)}
export function quoteRepair(bookId:string,chapter:number,passage:string,body:CreateAudiobookRepairRequest,signal?:AbortSignal):Promise<CloudSpeechQuote>{return apiFetch(`/api/audiobooks/${id(bookId)}/chapters/${index(chapter)}/passages/${id(passage)}/repairs/quote`,json(parseCreateAudiobookRepairRequest(body),signal),parseCloudSpeechQuote)}
export function quoteControl(bookId:string,body:AudiobookCloudControlRequest,signal?:AbortSignal):Promise<CloudSpeechQuote>{return apiFetch(`/api/audiobooks/${id(bookId)}/cloud-quote`,json(parseAudiobookCloudControlRequest(body),signal),parseCloudSpeechQuote)}
