# Narrow used APIs inspected against PyTorch v2.6.0 torch/serialization.py and
# torch/_C/__init__.pyi. Optional runner only; deliberately no broader fake API.
from collections.abc import Sequence
from contextlib import AbstractContextManager
from typing import IO, Literal
class Tensor:
    def unsqueeze(self, dim:int)->Tensor: ...
    def detach(self)->Tensor: ...
    def cpu(self)->Tensor: ...
    def reshape(self, *shape:int)->Tensor: ...
    def tolist(self)->object: ...
float32:object
def tensor(data:Sequence[float],*,dtype:object)->Tensor: ...
def ones(*size:int)->Tensor: ...
def load(f:IO[bytes],*,map_location:str,weights_only:Literal[True])->object: ...
def set_num_threads(count:int)->None: ...
def inference_mode()->AbstractContextManager[None]: ...
