export const videoDialogueEn = {
  title: 'Cast dialogue', hint: 'Your completed cast recordings drive the soundtrack. Pictures render silently; this does not synchronize lips. Up to four clips, six seconds each, fifteen seconds including padding. Shot timing follows the saved dialogue.',
  filmstrip: 'Sampled frames from shot {number}', soundtrack: 'Original cast soundtrack', waveform: 'Waveform for {speaker}', caption: 'Caption for this clip',
  clipStart: 'Start in source (ms)', clipEnd: 'End in source (ms)', boundsHint: 'Leave bounds blank to keep the current trim, or refresh a whole passage in full. Edited bounds require a caption for those selected words.', refreshTitle: 'Use a repaired passage', refreshHint: 'Keep this shot’s duration and replace its audio from the latest accepted audiobook passage. Only this shot loses approval. Review the caption against the selected audio.', refresh: 'Refresh this line', redo: 'Redo saved change',
  reviewTitle: 'Review training examples', captionHint: 'Describe this example’s pose, expression, clothing and setting. Reserve at least one different photo for evaluation; it never enters training.', heldOut: 'Evaluation only', datasetReviewed: 'I reviewed every caption and the training/evaluation split', steps: 'Training steps', rank: 'LoRA rank', customTrainer: 'Custom trainer configured. Dependency and model compatibility checks remain the operator’s responsibility.', dependenciesMissing: 'Trainer dependencies are unavailable. Configure the video engine Python with the trainer extra installed.',
  compare: 'Create held-out comparison', baseline: 'Open still baseline', adapted: 'Open LoRA comparison', reviewNotes: 'Comparison notes', review: 'Record reviewed comparison', reviewHint: 'Render both fixed-prompt projects with matching settings and review identity across all shots before recording your findings. A review is your assessment, not an automatic quality score.', evaluated: 'Comparison reviewed', pending: 'Likeness has not been evaluated',
}
export const videoDialogueErrorsEn = {
  passage_changed: 'The source passage changed. Refresh the audiobook selection.', passage_not_ready: 'This passage has no completed recording.', dialogue_clip_bounds: 'Select 0.2 to 6 seconds of source audio within this shot’s duration.', dialogue_reel_limit: 'The selected clips and padding exceed the fifteen-second reel limit.', dialogue_caption_limit: 'Provide a caption of at most 500 characters.', dialogue_clip_caption_required: 'A trimmed clip needs a caption matching the selected words.', dialogue_timing_locked: 'Dialogue shot timing follows its saved audio. Edit prompts or refresh the source line instead.', dialogue_soundtrack_managed: 'This soundtrack is assembled from cast cues. Refresh the selected line to change it.',
  nothing_to_undo: 'There is no saved change to undo.', nothing_to_redo: 'There is no saved change to redo.', history_invalid: 'This historical change belongs to a different project. The current project was preserved.', history_media_missing: 'Historical media is missing. The current project was preserved.', caption_glyph_unavailable: 'A caption contains a character outside the bundled fonts. Use supported Latin, Greek, Cyrillic, Han, kana or Hangul text.', caption_font_unavailable: 'The bundled caption font is missing or changed. Reinstall the app assets.',
  dataset_review_required: 'Review captions and reserve a separate evaluation photo before training.', dataset_item_mismatch: 'The reviewed examples do not match the uploaded files.', held_out_required: 'Use at least three training photos and one separate evaluation photo.', held_out_overlap: 'An evaluation example duplicates training media. Choose a different reference.', character_adapter_incompatible: 'This adapter was trained for a different base model. Use LTX-2.3.', trainer_dependencies_missing: 'The configured Python lacks the video trainer dependencies.', character_dataset_unreviewed: 'This older adapter has no reviewed dataset provenance.', character_comparison_required: 'Render both unchanged comparison projects and review every fixed-prompt shot first.',
}
