# Inspected SpeechBrain v1.0.3 speechbrain/processing/features.py InputNormalization.
from torch import Tensor
class InputNormalization:
    def __init__(self,*,norm_type:str,std_norm:bool)->None: ...
    def __call__(self,features:Tensor,lengths:Tensor)->Tensor: ...
