# Inspected SpeechBrain v1.0.3 speechbrain/lobes/features.py Fbank.
from torch import Tensor
class Fbank:
    def __init__(self,*,n_mels:int)->None: ...
    def __call__(self,wav:Tensor)->Tensor: ...
