"""Narrow native backend declaration, inspected in keyring25.7.0 source."""
class Keyring:
    def __init__(self) -> None: ...
    @property
    def priority(self) -> float: ...
    def get_password(self, service: str, username: str) -> str | None: ...
    def set_password(self, service: str, username: str, password: str) -> None: ...
    def delete_password(self, service: str, username: str) -> None: ...
